name: Gif Comment
on:
  issues:
    types: [opened]

jobs:
  comment:
    if: github.event_name == 'issues'
    steps:
      - name: Add funny comment
        uses: Marta83/funny-comment-action@v2.1
        id: FunnyComment
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIPHY_KEY: ${{ secrets.GIPHY_KEY }} 
          comments_type: 'gif' 
